#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
RESET='\033[0m'

set -e

# Check if the user is in the project root directory
if [ ! -e "manage.py" ]; then
    printf "${RED}You should run git merge under the root directory of this project.${RESET}\n"
    exit 1
fi

echo "Updating git hooks..."
bash ./scripts/dev/installgithooks.sh
printf "${GREEN}Git hooks updated successfully.${RESET}\n"
