# Generated by Django 3.2.20 on 2024-01-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_id',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='oauth_org',
            field=models.CharField(choices=[('google', 'google'), ('facebook', 'facebook')], default='google', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('oauth_org', 'oauth_id')},
        ),
    ]
