# Generated by Django 3.0.3 on 2021-07-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.BigIntegerField()),
                ('sid', models.CharField(max_length=32)),
                ('comanyName', models.CharField(max_length=32)),
                ('tradeType', models.CharField(max_length=32)),
                ('qyantity', models.BigIntegerField()),
                ('openPrice', models.FloatField()),
                ('closePrice', models.FloatField()),
                ('highestPrice', models.FloatField()),
                ('lowestPrice', models.FloatField()),
                ('fluctPrice', models.FloatField()),
                ('fluctRate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealTime', models.BigIntegerField()),
                ('sid', models.CharField(max_length=32)),
                ('comanyName', models.CharField(max_length=32)),
                ('dealPrice', models.FloatField()),
                ('dealQuantity', models.BigIntegerField()),
                ('handlingFee', models.BigIntegerField()),
            ],
        ),
    ]
