# Generated by Django 3.0.3 on 2021-07-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfoScraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinfo',
            old_name='comanyName',
            new_name='companyName',
        ),
        migrations.RenameField(
            model_name='traderecord',
            old_name='comanyName',
            new_name='companyName',
        ),
    ]
