# Generated by Django 3.1.4 on 2021-07-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfoScraper', '0003_auto_20210714_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDividendRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealTime', models.BigIntegerField()),
                ('sid', models.CharField(max_length=32)),
                ('companyName', models.CharField(max_length=32)),
                ('cashDividend', models.BigIntegerField()),
            ],
        ),
    ]
