# Generated by Django 3.0.3 on 2021-10-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfoScraper', '0004_cashdividendrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=32)),
                ('mainGoodsOrServices', models.CharField(max_length=128)),
                ('strategyUsed', models.CharField(max_length=32)),
                ('myNote', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TradePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=32)),
                ('planType', models.CharField(max_length=32)),
                ('targetPrice', models.FloatField()),
                ('targetQuantity', models.BigIntegerField()),
            ],
        ),
    ]
