# Generated by Django 3.2 on 2021-12-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfoScraper', '0005_stockmemo_tradeplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='closePrice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='fluctPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='fluctRate',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='highestPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='lowestPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='openPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='targetPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='traderecord',
            name='dealPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
