# Generated by Django 3.2 on 2021-12-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfoScraper', '0006_auto_20211214_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='closePrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='fluctPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='fluctRate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='highestPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='lowestPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='openPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='targetPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='traderecord',
            name='dealPrice',
            field=models.FloatField(),
        ),
    ]
