# Generated by Django 3.2 on 2022-02-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfoScraper', '0007_auto_20211214_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=32)),
                ('login_token', models.CharField(blank=True, max_length=512, null=True, unique=True)),
            ],
        ),
    ]
