# Generated by Django 3.2 on 2022-02-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfoScraper', '0008_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashDividendRecord',
            new_name='cash_dividend_record',
        ),
        migrations.RenameModel(
            old_name='StockInfo',
            new_name='stock_info',
        ),
        migrations.RenameModel(
            old_name='StockMemo',
            new_name='stock_memo',
        ),
        migrations.RenameModel(
            old_name='TradePlan',
            new_name='trade_plan',
        ),
        migrations.RenameModel(
            old_name='TradeRecord',
            new_name='trade_record',
        ),
    ]
