# Generated by Django 3.2 on 2022-02-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stockInfoScraper", "0011_auto_20220221_1913"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="id",
        ),
        migrations.AlterField(
            model_name="company",
            name="stock_id",
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="cash_dividend_record",
            name="company",
            field=models.ForeignKey(
                default="0050",
                on_delete=django.db.models.deletion.PROTECT,
                to="stockInfoScraper.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock_info",
            name="company",
            field=models.ForeignKey(
                default="0050",
                on_delete=django.db.models.deletion.PROTECT,
                to="stockInfoScraper.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock_memo",
            name="company",
            field=models.ForeignKey(
                default="0050",
                on_delete=django.db.models.deletion.PROTECT,
                to="stockInfoScraper.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trade_record",
            name="company",
            field=models.ForeignKey(
                default="0050",
                on_delete=django.db.models.deletion.PROTECT,
                to="stockInfoScraper.company",
            ),
            preserve_default=False,
        ),
    ]
