# Generated by Django 3.2 on 2022-02-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfoScraper', '0012_auto_20220221_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade_plan',
            name='company',
            field=models.ForeignKey(default='0050', on_delete=django.db.models.deletion.PROTECT, to='stockInfoScraper.company'),
            preserve_default=False,
        ),
    ]
