# Generated by Django 3.2 on 2022-02-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfoScraper', '0013_trade_plan_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash_dividend_record',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='cash_dividend_record',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='stock_info',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='stock_info',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='stock_memo',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='trade_plan',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='trade_record',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='trade_record',
            name='sid',
        ),
    ]
