services:
    api-server:
        build:
            context: ./api-server
            dockerfile: Dockerfile
            target: dev_final
            tags:
                - trade-smartly-api-server:dev
        volumes:
            - ./api-server:/app:cached
        command: ["gunicorn"]
        env_file: .env
        ports:
            - "8000:8000"
        depends_on:
            - redis
            - db
        restart: unless-stopped
        logging:
          driver: "json-file"
          options:
            max-size: "2m"
            max-file: "1"
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: dev_final
            tags:
                - trade-smartly-frontend:dev
        volumes:
            - frontend_node_modules:/app/node_modules # This also prevents node_modules/ from being synced back to the code base
            - ./frontend:/app:cached
        command: ["npm", "run", "dev"]
        ports:
            - "3000:3000"
        depends_on:
            - api-server
        restart: unless-stopped
        logging:
          driver: "json-file"
          options:
            max-size: "2m"
            max-file: "1"
    reverse-proxy:
        image: nginx:1.27.4
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./reverse-proxy/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
            - ./reverse-proxy/dev-cert.pem:/etc/ssl/certs/trade-smartly.com/cert.pem:ro
            - ./reverse-proxy/dev-key.pem:/etc/ssl/certs/trade-smartly.com/key.pem:ro
        command: ["nginx", "-g", "daemon off;"]
        restart: unless-stopped
        logging:
          driver: "json-file"
          options:
            max-size: "2m"
            max-file: "1"
    redis:
        image: redis:6.2.17
        ports:
            - "6380:6379"
        volumes:
            - redis_data:/data
        restart: unless-stopped
        logging:
          driver: "json-file"
          options:
            max-size: "2m"
            max-file: "1"
    db:
        image: postgres:16.8
        ports:
            - "5433:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh # This will be executed when the container starts
        environment:
            - PGUSER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres # for default, the application doesn't use this
            - APP_DB=trade_smartly
        restart: unless-stopped
        logging:
          driver: "json-file"
          options:
            max-size: "2m"
            max-file: "1"
    scheduler:
        build:
            context: ./api-server
            dockerfile: Dockerfile
            target: dev_final
            tags:
                - trade-smartly-scheduler:dev
        volumes:
            - ./api-server/scheduler.py:/app/scheduler.py:ro
        command: ["python", "-u", "scheduler.py"]
        depends_on:
            - redis
            - db
        restart: unless-stopped
        logging:
          driver: "json-file"
          options:
            max-size: "2m"
            max-file: "1"

volumes:
    redis_data:
    db_data:
    frontend_node_modules:
