services:
    api-server:
        build:
            context: ./api-server
            dockerfile: Dockerfile
            target: prod_final
            tags:
                - trade-smartly-api-server:prod
        command: ["gunicorn"]
        env_file: .env
        expose:
            - "8000"
        depends_on:
            - redis
            - db
        restart: unless-stopped
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: prod_final
            tags:
                - trade-smartly-frontend:prod
        command: ["serve", "-s", "build", "-l", "3000"]
        expose:
            - "3000"
        depends_on:
            - api-server
        restart: unless-stopped
    reverse-proxy:
        image: nginx:1.27.4
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - /etc/letsencrypt/live/trade-smartly.com:/etc/letsencrypt/live/trade-smartly.com:ro
            - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro
            - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem:ro
        command: ["nginx", "-g", "daemon off;"]
        restart: unless-stopped
    redis:
        image: redis:6.2.17
        expose:
            - "6379"
        volumes:
            - redis_data:/data
        restart: unless-stopped
    db:
        image: postgres:16.8
        expose:
            - "5432"
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh # This will be executed when the container starts
        environment:
            - PGUSER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres # for default, the application doesn't use this
            - APP_DB=trade_smartly
        restart: unless-stopped
    scheduler:
        build:
            context: ./api-server
            dockerfile: Dockerfile
            target: prod_final
            tags:
                - trade-smartly-scheduler:prod
        volumes:
            - ./api-server/scheduler.py:/app/scheduler.py:ro
        command: ["python", "-u", "scheduler.py"]
        depends_on:
            - redis
            - db
        restart: unless-stopped

volumes:
    redis_data:
    db_data:
