services:
  api-server:
    image: taigutw/api-server:prod
    volumes:
      - ./api-server/google_client_secret.json:/app/google_client_secret.json:ro
    command: ["gunicorn"]
    env_file: .env
    expose:
      - "8000"
    depends_on:
      - redis
      - db
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
  frontend:
    image: taigutw/frontend:prod
    command: ["serve", "-s", "build", "-l", "3000"]
    expose:
      - "3000"
    depends_on:
      - api-server
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
  reverse-proxy:
    image: nginx:1.27.4
    user: root
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/ssl/certs/cloudflare-cert.pem:/etc/ssl/certs/cloudflare-cert.pem:ro
      - /etc/ssl/certs/cloudflare-private-key.pem:/etc/ssl/certs/cloudflare-private-key.pem:ro
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - api-server
      - frontend
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
  redis:
    image: redis:7.4.4-alpine
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
  db:
    image: postgres:16.8
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taigu
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
  scheduler:
    image: taigutw/scheduler:prod
    command: ["python", "-u", "main.py"]
    env_file: .env
    depends_on:
      - redis
      - db
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"

volumes:
  redis_data:
  db_data:
