#!/usr/bin/env bash

cat <<EOF >.env
DB_NAME=trade_smartly
DB_USER=postgres
DB_PASSWORD=0000
DB_HOST=localhost
SECRET_KEY=jerkn578fih4j5ytfiruyvw458fij9h78ridj834
DJANGO_SETTINGS_MODULE=main.settings
EOF
