#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
RESET='\033[0m'

set -e

if [ ! -d ".git" ]; then
    printf "${RED}Wrong directory: $(pwd).${RESET}\n"
    exit 1
fi

printf "${BLUE}Updating git hooks...${RESET}\n"
bash ./scripts/dev/install-git-hooks.sh
printf "${GREEN} ✔ Git hooks updated${RESET}\n"
