# Generated by Django 5.2.5 on 2025-11-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_id_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='oauth_id',
            field=models.CharField(max_length=64),
        ),
    ]
