# Generated by Django 5.0.3 on 2024-05-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockmemo",
            name="business",
        ),
        migrations.RemoveField(
            model_name="stockmemo",
            name="strategy",
        ),
    ]
