# Generated by Django 5.0.3 on 2024-05-02 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0002_remove_stockmemo_business_remove_stockmemo_strategy"),
        ("stock", "0003_company_business"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmemo",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memos",
                to="stock.company",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockmemo",
            unique_together={("owner", "company")},
        ),
    ]
