# Generated by Django 5.0.7 on 2024-09-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
