# Generated by Django 5.2.5 on 2025-12-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdividendrecord',
            name='cash_dividend',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='quantity',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='quantity',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='traderecord',
            name='handling_fee',
            field=models.PositiveBigIntegerField(),
        ),
    ]
