# Generated by Django 5.0.7 on 2025-08-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stockinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business',
            field=models.TextField(db_default=''),
        ),
        migrations.AlterField(
            model_name='history',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY')], db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='materialfact',
            name='description',
            field=models.TextField(db_default=''),
        ),
        migrations.AlterField(
            model_name='materialfact',
            name='title',
            field=models.TextField(db_default=''),
        ),
    ]
