# Generated by Django 5.2.5 on 2025-11-30 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_company_business_alter_history_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='company',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stock.company'),
        ),
        migrations.AlterField(
            model_name='marketindexperminute',
            name='market',
            field=models.CharField(choices=[('tse', 'tse'), ('otc', 'otc')], max_length=4),
        ),
        migrations.AlterField(
            model_name='materialfact',
            name='company',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='material_facts', to='stock.company'),
        ),
    ]
