# Generated by Django 3.2.16 on 2023-01-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade_plan',
            name='company',
        ),
        migrations.RemoveField(
            model_name='trade_plan',
            name='owner',
        ),
        migrations.DeleteModel(
            name='stock_memo',
        ),
        migrations.DeleteModel(
            name='trade_plan',
        ),
    ]
