# Generated by Django 3.2.16 on 2023-02-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20230109_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_info', to='stock.company'),
        ),
    ]
