# Generated by Django 3.2.18 on 2023-02-28 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20230201_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY')], default='DAILY', max_length=8)),
                ('date', models.DateField()),
                ('quantity', models.BigIntegerField()),
                ('close_price', models.FloatField()),
                ('fluct_price', models.FloatField()),
                ('fluct_rate', models.FloatField()),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='trade_type',
            field=models.CharField(choices=[('tse', 'tse'), ('otc', 'otc')], max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='StockInfo',
        ),
        migrations.AddField(
            model_name='history',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stock.company'),
        ),
    ]
