# Generated by Django 3.2.18 on 2023-02-28 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20230228_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stock.company'),
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('company', 'frequency', 'date')},
        ),
    ]
