# Generated by Django 3.2.18 on 2023-02-28 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20230228_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('quantity', models.BigIntegerField()),
                ('close_price', models.FloatField()),
                ('fluct_price', models.FloatField()),
                ('fluct_rate', models.FloatField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_info', to='stock.company')),
            ],
            options={
                'db_table': 'stock_info',
            },
        ),
    ]
