# Generated by Django 3.2.18 on 2023-02-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='fluct_rate',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='fluct_rate',
        ),
    ]
