# Generated by Django 3.2.18 on 2023-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20230228_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY')], db_index=True, default='DAILY', max_length=8),
        ),
    ]
