# Generated by Django 3.2.18 on 2023-03-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20230301_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='fluct_price',
        ),
    ]
