# Generated by Django 3.2.16 on 2023-01-06 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_auto_20230106_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='trade_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_type', models.CharField(max_length=32)),
                ('target_price', models.FloatField()),
                ('target_quantity', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='stock_memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.CharField(max_length=2048)),
                ('strategy', models.CharField(max_length=128)),
                ('note', models.CharField(max_length=4096)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='stock.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_memos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
