# Generated by Django 3.2.16 on 2023-01-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_memo',
            name='business',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stock_memo',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stock_memo',
            name='strategy',
            field=models.TextField(default=''),
        ),
    ]
