services:
    api-server:
        build:
            context: ../api-server
            dockerfile: Dockerfile
            target: dev_final
        volumes:
            - ..:/app:cached
        command: ["sleep", "infinity"]
    frontend:
        build:
            context: ../frontend
            dockerfile: Dockerfile
            target: dev_final
        volumes:
            - ..:/app:cached
        command: ["sleep", "infinity"]
