# Generated by Django 5.2.5 on 2025-12-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeplan',
            name='target_quantity',
            field=models.PositiveBigIntegerField(),
        ),
    ]
