# Generated by Django 5.0.7 on 2025-08-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmemo',
            name='note',
            field=models.TextField(db_default=''),
        ),
    ]
