# Generated by Django 5.2.5 on 2025-11-30 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0006_alter_stockmemo_company_alter_stockmemo_owner'),
        ('stock', '0004_alter_company_business_alter_history_frequency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmemo',
            name='company',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='memos', to='stock.company'),
        ),
        migrations.AlterField(
            model_name='stockmemo',
            name='owner',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='stock_memos', to=settings.AUTH_USER_MODEL),
        ),
    ]
