# Generated by Django 5.2.5 on 2025-11-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0007_alter_stockmemo_company_alter_stockmemo_owner'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockmemo',
            name='idx_stock_memo_company',
        ),
    ]
