# Generated by Django 3.2.20 on 2023-09-04 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('stock_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('trade_type', models.CharField(choices=[('tse', 'tse'), ('otc', 'otc')], max_length=4, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal_time', models.DateField()),
                ('deal_price', models.FloatField()),
                ('deal_quantity', models.BigIntegerField()),
                ('handling_fee', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trade_record',
            },
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('quantity', models.BigIntegerField()),
                ('close_price', models.FloatField()),
                ('fluct_price', models.FloatField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_info', to='stock.company')),
            ],
            options={
                'db_table': 'stock_info',
            },
        ),
        migrations.CreateModel(
            name='CashDividendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal_time', models.DateField()),
                ('cash_dividend', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_dividend_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cash_dividend_record',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY')], db_index=True, default='DAILY', max_length=8)),
                ('date', models.DateField()),
                ('quantity', models.BigIntegerField()),
                ('close_price', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stock.company')),
            ],
            options={
                'db_table': 'history',
                'unique_together': {('company', 'frequency', 'date')},
            },
        ),
    ]
