# Generated by Django 3.2.20 on 2023-12-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketIndexPerMinute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "market",
                    models.CharField(
                        choices=[("tse", "tse"), ("otc", "otc")],
                        db_index=True,
                        max_length=4,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("number", models.PositiveSmallIntegerField(db_index=True)),
                ("price", models.FloatField()),
                ("fluct_price", models.FloatField()),
            ],
            options={
                "db_table": "market_index_per_minute",
                "unique_together": {("market", "date", "number")},
            },
        ),
    ]
