# Generated by Django 5.0.3 on 2024-05-01 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("timestamp", models.PositiveIntegerField()),
                ("title", models.TextField(default="")),
                ("description", models.TextField(default="")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_facts",
                        to="stock.company",
                    ),
                ),
            ],
            options={
                "db_table": "material_fact",
                "unique_together": {("company", "date", "timestamp")},
            },
        ),
    ]
