# Generated by Django 5.0.7 on 2024-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_alter_history_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockinfo",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
