# Generated by Django 5.0.3 on 2024-05-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_materialfact"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="business",
            field=models.TextField(default=""),
        ),
    ]
