# Generated by Django 5.0.3 on 2024-05-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_company_business"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialfact",
            name="date_time",
            field=models.DateTimeField(null=True),
        ),
    ]
