# Generated by Django 5.0.3 on 2024-05-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_materialfact_date_time"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="materialfact",
            unique_together={("company", "date_time")},
        ),
        migrations.AlterField(
            model_name="materialfact",
            name="date_time",
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name="materialfact",
            name="date",
        ),
        migrations.RemoveField(
            model_name="materialfact",
            name="timestamp",
        ),
    ]
