# Generated by Django 5.2.9 on 2026-05-17 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('trade_record', 'Trade record')], max_length=64)),
                ('subject_id', models.CharField(max_length=64)),
                ('revision', models.PositiveBigIntegerField()),
                ('operation', models.CharField(choices=[('upsert', 'Upsert'), ('delete', 'Delete')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_change_log',
                'indexes': [models.Index(fields=['created_at'], name='data_change_log_created_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'subject', 'revision'), name='unique_user_subject_revision')],
            },
        ),
    ]
