name: Build and push production images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push-production-images:
    runs-on: ubuntu-latest
    environment: Build
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: make build-prod
      - name: Push
        run: make push-images-prod
